# makefile header for vile utilities using DJGPP.
# From the top-makefile.djg, do
#	make -f makefile.djg flt=y
#
# $Id: makefile.djg,v 1.6 2020/09/08 19:53:06 tom Exp $

CC = gcc
LINK = gcc
LEX = flex
x = .exe
o = .o

AR = ar
ARFLAGS = crv
RANLIB = ranlib

DEBUG = -g
#OPTIM =

#DEBUG =
OPTIM = -O2

CFLAGS= -Wall $(DEBUG) $(OPTIM) -I. -I..

LIB_PREFIX=
LIBBUILTFLT=${LIB_PREFIX}vlflt.a
