@echo off
rem $Header: /users/source/archives/vile.vcs/filters/RCS/mk-1st.bat,v 1.4 2000/08/08 23:47:12 tom Exp $
rem like mk-1st.awk, used to generate lists from genmake.mak

echo # generated by %0.bat

goto %2

:extern
echo ALL_C	= \
genmake.exe -c "	vile-%%i-filt$x %%b" <%1
echo.
if "%LEX%" == "" goto done
echo ALL_LEX	= \
genmake.exe -l "	vile-%%i-filt$x %%b" <%1
echo.
goto done

:intern
echo OBJ_C	= \
genmake.exe -c "	%%j$o %%b" <%1
echo.
echo OBJ_LEX	= \
genmake.exe -l "	%%j$o %%b" <%1
echo.
goto done

:done

echo KEYS	= \
FOR %%i in (*.key) do echo 	%%i \
