@echo off
rem $Header: /users/source/archives/vile.vcs/filters/RCS/mk-1st.bat,v 1.5 2000/08/16 09:49:58 tom Exp $
rem like mk-1st.awk, used to generate lists from genmake.mak

genmake.exe -n "# generated by %0.bat

goto %2

:extern
genmake.exe -n "ALL_C	= %%b"
genmake.exe -c "	vile-%%i-filt$x %%b" <%1
genmake.exe -n ""
if "%LEX%" == "" goto done
genmake.exe -n "ALL_LEX	= %%b"
genmake.exe -l "	vile-%%i-filt$x %%b" <%1
genmake.exe -n ""
goto done

:intern
genmake.exe -n "OBJ_C	= %%b"
genmake.exe -c "	%%j$o %%b" <%1
genmake.exe -n ""
genmake.exe -n "OBJ_LEX	= %%b"
genmake.exe -l "	%%j$o %%b" <%1
genmake.exe -n ""
goto done

:done

genmake.exe -n "KEYS	= %%b"
FOR %%i in (*.key) do genmake.exe -n "	%%i %%b"
genmake.exe -n ""
